export const ADD_CITY = "ADD_CITY";
export const REMOVE_CITY = "REMOVE_CITY";
export const LOAD_CITY_FAILURE = "LOAD_CITY_FAILURE";
export const LOAD_CITY_IN_PROGRESS = "LOAD_CITY_IN_PROGRESS";
export const LOAD_CITY_WEATHER_SUCCESS = "LOAD_CITY_WEATHER_SUCCESS";
export const LOAD_CITY_FORCAST_SUCCESS = "LOAD_CITY_FORCAST_SUCCESS";
